CREATE TABLE IF NOT EXISTS repositories (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    user_login VARCHAR(255) NOT NULL,
    setup BOOLEAN,
    env_uri VARCHAR(255),
    created_by VARCHAR(255) ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE repositories
ALTER COLUMN setup SET DEFAULT FALSE;